// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/kube/client.go

// Package kube is a generated GoMock package.
package kube

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	rest "k8s.io/client-go/rest"
)

// MockK8sRESTClientFactory is a mock of K8sRESTClientFactory interface.
type MockK8sRESTClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockK8sRESTClientFactoryMockRecorder
}

// MockK8sRESTClientFactoryMockRecorder is the mock recorder for MockK8sRESTClientFactory.
type MockK8sRESTClientFactoryMockRecorder struct {
	mock *MockK8sRESTClientFactory
}

// NewMockK8sRESTClientFactory creates a new mock instance.
func NewMockK8sRESTClientFactory(ctrl *gomock.Controller) *MockK8sRESTClientFactory {
	mock := &MockK8sRESTClientFactory{ctrl: ctrl}
	mock.recorder = &MockK8sRESTClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8sRESTClientFactory) EXPECT() *MockK8sRESTClientFactoryMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockK8sRESTClientFactory) Client(group, version string) (*rest.RESTClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client", group, version)
	ret0, _ := ret[0].(*rest.RESTClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Client indicates an expected call of Client.
func (mr *MockK8sRESTClientFactoryMockRecorder) Client(group, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockK8sRESTClientFactory)(nil).Client), group, version)
}

// Request mocks base method.
func (m *MockK8sRESTClientFactory) Request(r http.Request) (*rest.Request, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", r)
	ret0, _ := ret[0].(*rest.Request)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockK8sRESTClientFactoryMockRecorder) Request(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockK8sRESTClientFactory)(nil).Request), r)
}
